#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_activation:
    path: '/user/{idUser}/activate'
    controller: 'App\Controller\UtilisateurController::activateUser'
